<?php

include_once('ec_content.features.inc');


// change to viewfield?
function ec_content_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {

  switch ($op) {
    case 'insert':

	break;
    case 'presave':

    break;
    case 'view':

      if($node->field_image && $node->field_image[0]['fid']){
	    $node->content['ddblock'] = array(
			'#value' => views_embed_view('node_gallery','page_1',array($node->nid)),
			'#weight' => $node->content['group_images']['#weight'],
	    );
	  }

      break;
   }

}
