<?php

/**
 * Implementation of hook_footer().
 */
function ec_footer_footer($main = 0) {
  
  if (variable_get('ec_footer','1') == 1){
    return '<div id="ec_logo_footer" style="background-color:#000;text-align:right;margin-top:20px;">
      <div><a href="http://www.essential-connections.com" ><img src="http://www.essential-connections.com/ec_logo_footer.png"></img></a></div>
    </div>';
  }
  
}
